import React from 'react';
import { ScrollView, StyleSheet, Text } from 'react-native';
import { theme } from '@/config/theme';
import { ScreenContainer } from '@/components/ScreenContainer';

const sections = [
  {
    title: '1. Welcome to PUBSTORE',
    body: 'These Terms of Service ("Terms") govern your access to and use of PUBSTORE, the social marketplace platform that brings together products, stories, and people across marketplace, news, stays, autos, jobs, services, rides, logistics, and more. PUBSTORE is operated by PUBSTORE ("we", "us", or "our"). By using PUBSTORE, you agree to these Terms.',
  },
  {
    title: '2. Eligibility and accounts',
    body: 'You must be at least 18 years old to create an account. You are responsible for the accuracy of your account information and the confidentiality of your credentials. We may suspend or terminate accounts for violations, fraud, or extended inactivity.',
  },
  {
    title: '3. Definitions',
    body: 'Platform means the PUBSTORE website, apps, and related services. Buyer means a user who purchases or requests products or services. Supplier means a user who lists or provides products or services. Order means a transaction initiated by a Buyer. Wallet means the PUBSTORE Pay stored-value account. Escrow means the buyer-protection process where funds are held until delivery conditions are met. Content means any text, images, videos, reviews, listings, or other materials posted on the Platform.',
  },
  {
    title: '4. Buyer terms',
    body: 'When you place an Order, you are making an offer to purchase the listed item on the terms described. Prices are set by Suppliers and may change. Payment is processed through PUBSTORE Pay or approved third-party methods. Delivery terms depend on the Supplier and selected courier. If no courier is available, delivery may be negotiated directly. You may request a refund only if the product is not yet delivered and not yet marked as processing by the Supplier.',
  },
  {
    title: '5. Supplier terms',
    body: 'To list products or services, you must apply to become a Supplier and select a Supplier Plan (Free, Pro, or Elite). We charge a commission on the cost of goods sold (12% Free, 7% Pro, 4% Elite; shipping excluded). Suppliers must mark Orders as processing and delivered through the dashboard. Settlement occurs only after Buyer confirmation. Suppliers may not list prohibited, counterfeit, or illegal items.',
  },
  {
    title: '6. Wallet, payments, and refunds',
    body: 'PUBSTORE Pay is a stored-value wallet for payments, transfers, withdrawals, and AI credit purchases. Wallet balances are not bank deposits. Withdrawals are subject to verification and approval. Refunds are processed to the Buyer wallet when approved. We may recover funds when refunds, chargebacks, or reversals are necessary.',
  },
  {
    title: '7. Buyer protection and escrow',
    body: 'Payments for most Orders are held in escrow until the Buyer confirms receipt. The Supplier may mark delivered, but the Buyer must independently confirm. If a valid non-delivery or misdescription claim is raised, we may reverse the transaction and refund the Buyer from escrow.',
  },
  {
    title: '8. AI credits and AI features',
    body: 'AI features consume AI credits. Each account receives a limited number of free actions; additional actions require paid credits. AI outputs are generated by third-party models and are provided for convenience only. You are responsible for reviewing AI-generated content before publishing or acting on it.',
  },
  {
    title: '9. Rides, logistics, and services',
    body: 'Rides, logistics, and other services connect you with independent drivers, couriers, and providers. PUBSTORE facilitates the connection, payment, and dispute resolution, but the service contract is between you and the provider. Providers must comply with applicable licensing, insurance, and safety requirements.',
  },
  {
    title: '10. Prohibited conduct',
    body: 'You may not use PUBSTORE to violate laws, infringe rights, sell counterfeit or dangerous goods, engage in fraud or market manipulation, harass others, interfere with platform security, use unauthorized scraping or bots, or circumvent fees, escrow, or commissions.',
  },
  {
    title: '11. Intellectual property',
    body: 'PUBSTORE branding, trademarks, software, and content are owned by us or our licensors. You retain ownership of Content you post, but you grant us a worldwide, non-exclusive, royalty-free license to use it to operate and improve the Platform. You must have the right to post your Content.',
  },
  {
    title: '12. Dispute resolution',
    body: 'We encourage users to resolve disputes through direct communication and the in-app support center. PUBSTORE will make good-faith decisions based on available evidence. Nothing prevents either party from seeking injunctive relief or pursuing claims in a court of competent jurisdiction. The laws of South Africa govern these Terms, except where local consumer protection laws require otherwise.',
  },
  {
    title: '13. Limitation of liability',
    body: 'To the maximum extent permitted by law, PUBSTORE is not liable for indirect, incidental, special, consequential, or punitive damages. Our total liability is limited to the amount paid for the specific transaction giving rise to the claim, or the fees paid to PUBSTORE in the six months preceding the claim, whichever is higher.',
  },
  {
    title: '14. Termination and suspension',
    body: 'You may close your account at any time. We may suspend or terminate accounts, remove Content, or restrict features for violations, risk, or legal requirements. Upon termination, your rights to use the Platform cease, but payment, escrow, intellectual property, and dispute provisions survive.',
  },
  {
    title: '15. Changes to these Terms',
    body: 'We may update these Terms from time to time. We will notify you of material changes through the app, email, or a prominent notice. Continued use after changes take effect constitutes acceptance of the revised Terms.',
  },
  {
    title: '16. Contact us',
    body: 'Questions about these Terms? Contact us at legal@pubstore.app, help@pubstore.app, or through the in-app Help Center. Please also review our Privacy Policy.',
  },
];

export function TermsScreen() {
  return (
    <ScreenContainer title="Terms of Service">
      <ScrollView contentContainerStyle={{ padding: 20, gap: 12 }}>
        <Text style={styles.updated}>Last updated: 5 August 2026</Text>
        {sections.map((s, i) => (
          <React.Fragment key={i}>
            <Text style={styles.h2}>{s.title}</Text>
            <Text style={styles.p}>{s.body}</Text>
          </React.Fragment>
        ))}
      </ScrollView>
    </ScreenContainer>
  );
}

const styles = StyleSheet.create({
  updated: { color: theme.colors.muted, fontFamily: theme.fonts.body, fontSize: 12, marginBottom: 8 },
  h2: { fontFamily: theme.fonts.display, fontWeight: '700', color: theme.colors.foreground, fontSize: 16, marginTop: 8 },
  p: { color: theme.colors.foreground, fontFamily: theme.fonts.body, lineHeight: 20 },
});
