// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/search-products.ts
import { createClient } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^3.25.76";
function anonClient() {
  return createClient(
    process.env.SUPABASE_URL,
    process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
    { auth: { persistSession: false, autoRefreshToken: false } }
  );
}
var search_products_default = defineTool({
  name: "search_products",
  title: "Search products",
  description: "Search PUBSTORE marketplace products by keyword. Returns id, title, price, category, and supplier for each match.",
  inputSchema: {
    query: z.string().trim().min(1).describe("Keyword or phrase to match against product titles/descriptions."),
    category: z.string().trim().optional().describe("Optional category slug filter (e.g. 'electronics')."),
    limit: z.number().int().min(1).max(50).default(10).describe("Max results (1-50).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, category, limit }) => {
    const sb = anonClient();
    let q = sb.from("products").select("id,title,price,category,supplier_id,image_url,moq").ilike("title", `%${query}%`).limit(limit);
    if (category) q = q.eq("category", category);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { products: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-product.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^3.25.76";
var get_product_default = defineTool2({
  name: "get_product",
  title: "Get product",
  description: "Fetch full product details by product id.",
  inputSchema: {
    id: z2.string().describe("Product id (uuid).")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ id }) => {
    const sb = createClient2(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await sb.from("products").select("*").eq("id", id).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) return { content: [{ type: "text", text: "Product not found" }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { product: data }
    };
  }
});

// src/lib/mcp/tools/list-suppliers.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z3 } from "npm:zod@^3.25.76";
var list_suppliers_default = defineTool3({
  name: "list_suppliers",
  title: "List suppliers",
  description: "List PUBSTORE suppliers, optionally filtered by country or verified status.",
  inputSchema: {
    country: z3.string().trim().optional().describe("Country name filter."),
    verifiedOnly: z3.boolean().default(false).describe("Only return verified suppliers."),
    limit: z3.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ country, verifiedOnly, limit }) => {
    const sb = createClient3(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = sb.from("suppliers").select("id,name,country,verified,rating,response_rate").limit(limit);
    if (country) q = q.ilike("country", `%${country}%`);
    if (verifiedOnly) q = q.eq("verified", true);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { suppliers: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/search-jobs.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z4 } from "npm:zod@^3.25.76";
var search_jobs_default = defineTool4({
  name: "search_jobs",
  title: "Search jobs",
  description: "Search PUBSTORE job postings by keyword and optional location.",
  inputSchema: {
    query: z4.string().trim().min(1).describe("Keyword to match against job title or description."),
    location: z4.string().trim().optional().describe("Optional location filter."),
    limit: z4.number().int().min(1).max(50).default(15)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ query, location, limit }) => {
    const sb = createClient4(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = sb.from("job_postings").select("id,title,location,employment_type,salary_min,salary_max,company_id,created_at").ilike("title", `%${query}%`).limit(limit).order("created_at", { ascending: false });
    if (location) q = q.ilike("location", `%${location}%`);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { jobs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-properties.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z5 } from "npm:zod@^3.25.76";
var list_properties_default = defineTool5({
  name: "list_properties",
  title: "List properties",
  description: "List PUBSTORE property listings filtered by kind, city, or bedrooms.",
  inputSchema: {
    kind: z5.enum(["rent", "sale", "short_stay"]).optional().describe("Listing kind."),
    city: z5.string().trim().optional().describe("City filter."),
    minBedrooms: z5.number().int().min(0).optional(),
    limit: z5.number().int().min(1).max(50).default(20)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ kind, city, minBedrooms, limit }) => {
    const sb = createClient5(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    let q = sb.from("properties").select("*").limit(limit);
    if (kind) q = q.eq("kind", kind);
    if (city) q = q.ilike("city", `%${city}%`);
    if (typeof minBedrooms === "number") q = q.gte("bedrooms", minBedrooms);
    const { data, error } = await q;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { properties: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/latest-news.ts
import { createClient as createClient6 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z6 } from "npm:zod@^3.25.76";
var latest_news_default = defineTool6({
  name: "latest_news",
  title: "Latest news",
  description: "Fetch the latest PUBSTORE news articles.",
  inputSchema: {
    limit: z6.number().int().min(1).max(30).default(10)
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }) => {
    const sb = createClient6(
      process.env.SUPABASE_URL,
      process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY,
      { auth: { persistSession: false, autoRefreshToken: false } }
    );
    const { data, error } = await sb.from("news_articles").select("id,slug,title,excerpt,published_at,author").order("published_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { articles: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/create-rfq.ts
import { createClient as createClient7 } from "npm:@supabase/supabase-js@^2.104.0";
import { defineTool as defineTool7 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z7 } from "npm:zod@^3.25.76";
var create_rfq_default = defineTool7({
  name: "create_rfq",
  title: "Create RFQ",
  description: "Post a Request For Quote on behalf of the signed-in buyer. Suppliers will be able to quote against it.",
  inputSchema: {
    product: z7.string().trim().min(1).describe("Product name or short description."),
    quantity: z7.number().int().min(1).describe("Quantity required."),
    unit: z7.string().trim().default("pcs").describe("Unit (pcs, kg, tons, etc)."),
    targetPrice: z7.number().positive().optional().describe("Target unit price in USD."),
    destination: z7.string().trim().optional().describe("Destination country/city."),
    details: z7.string().trim().optional().describe("Additional requirements or notes.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false },
  handler: async (input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Sign-in required to post an RFQ." }], isError: true };
    }
    const sb = createClient7(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY ?? process.env.SUPABASE_ANON_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("rfqs").insert({
      buyer_id: ctx.getUserId(),
      product: input.product,
      quantity: input.quantity,
      unit: input.unit,
      target_price: input.targetPrice,
      destination: input.destination,
      details: input.details
    }).select().single();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `RFQ created: ${data.id}` }],
      structuredContent: { rfq: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "ccprnnqxpnrkdrfsudjc";
var mcp_default = defineMcp({
  name: "pubstore-mcp",
  title: "PUBSTORE",
  version: "0.1.0",
  instructions: "Tools for the PUBSTORE marketplace. Search products, suppliers, jobs, properties, and news; fetch product details; and post an RFQ on behalf of the signed-in buyer.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [search_products_default, get_product_default, list_suppliers_default, search_jobs_default, list_properties_default, latest_news_default, create_rfq_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
